#! /usr/bin/env ruby

require 'pathname'
ENV['BUNDLE_GEMFILE'] ||= File.expand_path("../../Gemfile",
  Pathname.new(__FILE__).realpath)

require 'rubygems'
require 'bundler/setup'
        
ciphertext = File.expand_path('ciphertext',
File.dirname(__FILE__))
ENV['SEKRETS_ARGV'] = "edit #{ ciphertext }"
        
exec(Gem.bin_path('sekrets', 'sekrets'))
