---
identifier: facebook_tabs

repository: git@github.com:dojo4/facebook-tabs.git

secret_token: ec759d3acccb0ce9c7aad88cf0c2319ec3d82723dbbb07ae5ab3d9dec8c8a4b0add9e7c72ffd34160752c6c8803da540824559901350b6c97595b2deaad459b7

staging:
  url: https://stagingfbtabs.digitalfusiontesting.com
  email_interceptor:
    model: EmailRedirectInterceptor
    to:
      - corey.inouye@mobilefusion.com
      - sheena.collins@mobilefusion.com

production:
  url: https://productionfbtabs.digitalfusiontesting.com

deploy:
  staging:
    ip: 198.61.171.226
    deploy_to: /var/www/stagingfbtabs.digitalfusiontesting.com

  production:
    ip: 198.61.171.226
    deploy_to: /var/www/productionfbtabs.digitalfusiontesting.com

  notify:
  - dojo4@dojo4.com


reports:
  model:
    model_names:
      - RFI
      - User

