uri        : http://xmlapi.iloopmobile.com/platform/group.ex?
web_uri    : http://webapi.iloopmobile.com/saturn/gateway/webin/https?
report_uri : http://xmlapi.iloopmobile.com/platform/reportApi/groupMessageDetails?
user_token : F9765E5B69F99EAB2956332B23EF55B1
short_code : 777555
keyword    : CCU
group_id   : 12445