#! /usr/bin/env ruby
# encoding: utf-8

unless DATA.flock(File::LOCK_EX | File::LOCK_NB) == 0
  exit!(42)
end

require(File.dirname(__FILE__) + '/../config/environment.rb')

unless STDIN.tty?
  log = Rails.root.join('log/locate_all_locations.log').to_s
  open(log, 'wb+') do |fd|
    STDOUT.reopen(fd)
    STDERR.reopen(fd)
  end
end

Location.locate_all! do |location|
  p location.full_address => location.loc
end

__END__
