#! /usr/bin/env ruby
# encoding: utf-8

##
#
  require 'fileutils'
  require 'rbconfig'

##
#
  mode = (ARGV.shift || 'restart').downcase
  rails_env = ARGV.shift || ENV['RAILS_ENV'] || 'production'
  port = ARGV.shift || ENV['APP_PORT'] || '3000'

## chdir
#
  script_dir = File.expand_path(File.dirname(__FILE__))
  rails_root = File.dirname(script_dir)
  Dir.chdir(rails_root)

## set path
#
  bindir = ::RbConfig::CONFIG['bindir']
  path = ENV['PATH']
  ENV['PATH'] = "#{ bindir }:#{ path }"


## clean up old passenger
#
  if mode == 'stop' || mode =='restart'
    system("passenger stop -p #{ port } --pid-file ./tmp/pids/passenger.#{ port }.pid")
  end

## start a new one
#
  if mode == 'start' || mode =='restart'
    system("passenger start -e #{ rails_env } -p #{ port } -d")
  end
