#!/usr/bin/env ruby

ENV[ "RAILS_EMAIL" ] = ENV[ "SMTP_DEBUG" ] = "1"

require File.expand_path('../../config/environment',  __FILE__)

email = ARGV.shift || abort('no email')

mail = Mailer.test( email ).deliver

puts
p mail
puts mail

